name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 24 hours
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - uses: claserre9/wakatime-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
